set -e
set -u

MODE=streaming
RUNNER=DataflowRunner
PERSISTENCE=STORAGE_WRITE_API
NUMBER_OF_STREAMS=$1
TRIGGERING_FREQUENCY=$2

./run-pipeline.sh ${MODE} ${RUNNER} ${PERSISTENCE} ${NUMBER_OF_STREAMS} ${TRIGGERING_FREQUENCY}
